name: Update stats

on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  waka:
    name: Update WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: looechao/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

  steam:
    name: Update Steam stats
    needs: waka
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - uses: looechao/steam-readme@master
        with:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
          COMMIT_MESSAGE: ":memo: update profile"
