name: Update steam playtime

on:
  repository_dispatch:
    types: [trigger_steam_box]

jobs:
  build:
    name: Update-steam-playtime
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Update Steam stats
        uses: looechao/steam-readme@master
        with:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
          COMMIT_MESSAGE: ":memo: update profile"
